In [ ]:
#Enlace a la información
#https://www.kaggle.com/code/residentmario/indexing-selecting-assigning

In [ ]:
import pandas as pd

In [ ]:
titanic_pasajeros = pd.read_csv("C:/Users/xabie/Desktop/gitProyectos/Python/datasets/Titanic-Dataset.csv" )

In [ ]:
titanic_pasajeros.head()

In [ ]:
titanic_pasajeros.Survived

In [ ]:
titanic_pasajeros['Survived']

In [ ]:
titanic_pasajeros["Name"][0]

In [ ]:
titanic_pasajeros.iloc[0]
#Iloc engancha la fila entera, con el índice de parámetro

In [ ]:
titanic_pasajeros.iloc[0 , 4] #fila primero, columa segundo

In [ ]:
#Para coger toda una columa, o fila se haría así
titanic_pasajeros.iloc[: , 1] #Así se sacan todos los datos de una columa
titanic_pasajeros.iloc[1 , :] #asi todos los datos de una fila

In [ ]:
titanic_pasajeros.iloc[:3 , :] #Esto es básicamente, todo hasta el 3
#De hacerlo al revés sería, todo menos los tres primeros .

In [ ]:
titanic_pasajeros.iloc[1:3 , 0 ] #ESto quiere decir del índice 1 (segunda fila , hasta la tercera, pero sólo el id (primera columna))

In [ ]:
titanic_pasajeros.iloc[[0 , 1 ,2 ,3 ] , 3] #Todos  los nombres de los 4 primeros

In [ ]:
titanic_pasajeros.iloc[-5 : ] #Los últimos 5
#si esta a la izquierda del los dos puntos, es

In [ ]:
#Acceso a datos usando el índice String
titanic_pasajeros.loc[0 , 'Name']

In [ ]:
titanic_pasajeros.loc[: , ['Name' , 'Survived']]
#TODAS LAS FILAS, QUE TENGAN ESOS CAMPOS DE COLUMNA

In [ ]:
titanic_pasajeros.set_index("Name")
#Para usar de índice una etiqueta (nombres de las columnas)

In [ ]:
titanic_pasajeros.set_index("Pclass")

In [54]:
titanic_pasajeros['Name'] == 'male'

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [51]:
titanic_pasajeros.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [64]:
titanic_pasajeros.loc[(titanic_pasajeros['Sex'] == 'male') & (titanic_pasajeros['Survived']) & (titanic_pasajeros['Fare'] > 20)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
23,24,1,1,"Sloper, Mr. William Thompson",male,28.00,0,0,113788,35.5000,A6,S
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
74,75,1,3,"Bing, Mr. Lee",male,32.00,0,0,1601,56.4958,NaN,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.00,0,1,PC 17759,63.3583,D10 D12,C
...,...,...,...,...,...,...,...,...,...,...,...,...
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C
838,839,1,3,"Chip, Mr. Chang",male,32.00,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.00,0,0,113055,26.5500,E17,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.00,0,0,111369,30.0000,C148,C

In [69]:
titanic_pasajeros.loc[(titanic_pasajeros['Fare'] > 2550 ) | (titanic_pasajeros['Sex'] == 'female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S