In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame({'Duros' : [ 'Xabi' , 'Javi'] , 'Blandos'
              : ['Wasoski' , 7] })

In [ ]:
pd.DataFrame({'Programadores' : ['Xabi' , 'Javi'] , 'Ricos' : ['1' , '1']}
             , index= ['Nombres' , 'CApacidad adquisitiva'] )

In [ ]:
pd.Series([1 , 2 ,3 ,4 ,5])
#Es básicamente , una lista normal y corriente, con sus índices empezando desde el 0

In [ ]:
pd.Series([120 , 120 ,700] , index= ['VEntas enero' , 'Ventas febrero' , 'Ventas marzo'])

In [30]:
titanic_pasajeros = pd.read_csv("C:/Users/xabie/Desktop/gitProyectos/Python/datasets/Titanic-Dataset.csv")

In [31]:
titanic_pasajeros.shape

(891, 12)

In [32]:
titanic_pasajeros.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [33]:
titanic_pasajeros = pd.read_csv("C:/Users/xabie/Desktop/gitProyectos/Python/datasets/Titanic-Dataset.csv" , index_col = 1)
titanic_pasajeros.head()
#Esto evidentemente , no tiene ninggun sentido, era por trastear.

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Survived,,,,,,,,,,,
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
1,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
0,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S